spring:
  application:
    name: Proyecto spring fullstack
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: false
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      # ddl-auto: none
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        connection:
          provider_disables_autocommit: true
        transaction:
          auto_commit: false
  sql:
    init:
      # mode: always
      mode: never
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
      continue-on-error: false
      platform: mysql
      encoding: UTF-8

server:
  port: ${PORT:8080}

logging:
  level:
    root: INFO
    com.proyectoSpring.fullstack: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.mysql.cj.jdbc: DEBUG
    org.springframework.jdbc.datasource.init: DEBUG
    org.springframework.boot.autoconfigure.jdbc: DEBUG

# Configuración JWT
jwt:
  secret: ${JWT_SECRET:tu_clave_secreta_muy_segura_para_el_token_jwt_debe_ser_muy_larga_y_segura}
  expiration: ${JWT_EXPIRATION:86400000} 